version: "3.9"
services:
  backend:
    build:
      context: ..
      dockerfile: app/backend/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - AZURE_OPENAI_ENDPOINT
      - AZURE_OPENAI_API_KEY
      - AZURE_API_VERSION
      - AZURE_MODEL_NAME
      - AZURE_DEPLOYMENT_NAME
      - ADO_ORG
      - GITHUB_PERSONAL_ACCESS_TOKEN
      - AZURE_CLIENT_ID
      - AZURE_CLIENT_SECRET
      - AZURE_TENANT_ID
      - AZURE_SUBSCRIPTION_ID
  frontend:
    build:
      context: ..
      dockerfile: app/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
    depends_on:
      - backend
